services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: linktree
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d linktree"]
      interval: 2s
      timeout: 5s
      retries: 10

  localstack:
    image: localstack/localstack:3
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
      - S3_BUCKET=avatars
    ports:
      - "4566:4566"
    volumes:
      - ./localstack/init/ready.d:/etc/localstack/init/ready.d

  kafka:
    image: confluentinc/confluent-local:7.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:29093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 10

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    env_file:
      - apps/api/.env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      # - /app/node_modules
      # - /app/apps/api/node_modules
    depends_on:
      db:
        condition: service_healthy
      localstack:
        condition: service_started
      kafka:
        condition: service_healthy

volumes:
  db_data:
